In [1]:
#importing the pandas and numpy
import pandas as pd 
import numpy as np

In [4]:
data = np.array([[1.5, -0.5, 1], [2.5, 0, -2.5]])
data

array([[ 1.5, -0.5,  1. ],
       [ 2.5,  0. , -2.5]])

In [5]:
data * 10

array([[ 15.,  -5.,  10.],
       [ 25.,   0., -25.]])

In [6]:
data * data

array([[2.25, 0.25, 1.  ],
       [6.25, 0.  , 6.25]])

In [7]:
data + data 


array([[ 3., -1.,  2.],
       [ 5.,  0., -5.]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [11]:
data = np.array(['shiva', 'jevis', 'anjelika', 'samprad', 'salina'])
data.dtype
data.shape

(5,)

In [14]:
data = [[2, -3.5, 2], [2.5, 3.5, 2]]
arr1 = np.array(data)
arr1.ndim
arr1.shape

(2, 3)

In [17]:
data = [[[2, 2], [2, 2]], [[1, 1], [1, 1]], [[3, 3], [3, 3]]]
arr = np.array(data)
arr.ndim
arr.shape
arr


array([[[2, 2],
        [2, 2]],

       [[1, 1],
        [1, 1]],

       [[3, 3],
        [3, 3]]])

In [19]:
np.zeros(10)
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv("train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
df = pd.read_csv("train.csv", header=None)
df.head()
df1 = pd.read_csv("train.csv", names=['a','b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k'])
df1.head()

a       b  \
PassengerId  Survived  Pclass   
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   

                                                             c       d    e  \
PassengerId                                               Name     Sex  Age   
1                                      Braund, Mr. Owen Harris    male   22   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38   
3                                       Heikkinen, Miss. Laina  female   26   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35   

                 f      g                 h        i      j         k  
PassengerId  SibSp  Parch            Ticket     Fare  Cabin  Embarked  
1                1      0         A/5 21171     7.25    NaN         S  
2                1      0          PC 17599  71.2833    C85         C  
3                0      0  STON/O2. 3101282    7.925    NaN         S  
4                1      0            113803     53.1   C123         S

In [9]:
names = ['id', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin','embarked']
df = pd.read_csv("train.csv", names=names, index_col='survived')
df.head()

#we can make the columns in the index

id  pclass  \
survived                        
Survived  PassengerId  Pclass   
0                   1       3   
1                   2       1   
1                   3       3   
1                   4       1   

                                                       name     sex  age  \
survived                                                                   
Survived                                               Name     Sex  Age   
0                                   Braund, Mr. Owen Harris    male   22   
1         Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38   
1                                    Heikkinen, Miss. Laina  female   26   
1              Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35   

          sibsp  parch            ticket     fare  cabin  embarked  
survived                                                            
Survived  SibSp  Parch            Ticket     Fare  Cabin  Embarked  
0             1      0         A/5 21171     7.25    NaN         S  
1             1      0          PC 17599  71.2833    C85         C  
1             0      0  STON/O2. 3101282    7.925    NaN         S  
1             1      0            113803     53.1   C123         S

In [10]:
parsed = pd.read_csv("train.csv", index_col=['key1', 'key2'])
parsed 

ValueError: Index key1 invalid

In [2]:
import pandas as pd
import numpy as np
data = pd.DataFrame({"something": ['one', 'two', 'three'], "a": [1, 5, 9], "b": [3.0, "NaN", 11.0], "c": [2, 6, 10], "message": ["NaN", "world", "foo"]})
df1 = pd.DataFrame(data)
df1


something  a     b   c message
0       one  1   3.0   2     NaN
1       two  5   NaN   6   world
2     three  9  11.0  10     foo

In [3]:
pd.isna(df1)

something      a      b      c  message
0      False  False  False  False    False
1      False  False  False  False    False
2      False  False  False  False    False

In [4]:
data = pd.DataFrame({"something": ['one', 'two', 'three'], "a": [1, 5, 9], "b": [3.0, np.NaN, 11.0], "c": [2, 6, 10], "message": [np.NaN, "world", "foo"]})
pd.isna(data)

something      a      b      c  message
0      False  False  False  False     True
1      False  False   True  False    False
2      False  False  False  False    False

In [1]:
#sep or delimiter -> character sequence or regular expression to use split fields in each row
#header -> default row or the first row but should be none if there is no header row row
#index_col -> column numbers or names to use as the row index in the result; can be a single name/ number or a list of them for a heirchical index 
#first row is alwayys header 
#first columns is always index_col
#names -> list of column names for result 
#keep_default_na = False is passed sequence of values to replace with NA. They are added to the default list unless keep_default_na = False 

In [8]:
data.isna()
data.isna()
data.isna()
data.isna()

something      a      b      c  message
0      False  False  False  False     True
1      False  False   True  False    False
2      False  False  False  False    False